spring:
  application:
    name: taskmanagement

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagement
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
        jdbc:
          time_zone: UTC

  jackson:
    time-zone: UTC

jwt:
  secret: 6u9qB0P8K2Yx3M7R5N1A9Z4L8C6V2X0Q5W7E1R3T9Y8U4I6O2P5S7D9F1G3H5J7
  expiration: 900000
  refresh-expiration: 604800000